- config: generic-flags
  flags:
    gpus: "1"
    workers: "0"
    checkpoint-monitor: "loss/train_avg"
    lr:
      type: float
    batch_size: 
      type: int
    gradient_clip_val:
      type: float
    encoder_hidden_layer_sizes: [512]
    decoder_hidden_layer_sizes: [512]

- config: model-base
  operations:
    synthetic:
        main: 'graph_nn_vae.experiments.synthetic.{{ name }}_training'
        flags:
            $include: generic-flags
        # output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"

                
- config: model-partial
  operations:
    sanity_checks:
        main: 'graph_nn_vae.experiments.sanity_checks.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"

- model: recurrent_autoencoder
  extends: model-base
  params:
    name: recurrent_autoencoder

- model: encoder_num_edges
  extends: model-partial
  params:
    name: encoder_num_edges
