- config: generic-flags
  flags:
    workers: "0"
    checkpoint_monitor: "loss/val"
    lr:
      type: float
    batch_size: 
      type: int
    gradient_clip_val:
      type: float
    seed:
      type: int

- config: model-base
  operations:
    synthetic_grid_small:
        main: 'rga.experiments.synthetic_grid_small.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    synthetic_grid_medium:
        main: 'rga.experiments.synthetic_grid_medium.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    synthetic_barabasi_small:
        main: 'rga.experiments.synthetic_barabasi_small.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    imdb_binary:
        main: 'rga.experiments.imdb_binary.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    imdb_multi:
        main: 'rga.experiments.imdb_multi.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    reddit_binary:
        main: 'rga.experiments.reddit_binary.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    reddit_multi_5k:
        main: 'rga.experiments.reddit_multi_5k.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    reddit_multi_12k:
        main: 'rga.experiments.reddit_multi_12k.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
    collab:
        main: 'rga.experiments.collab.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"
                
- config: model-partial
  operations:
    sanity_checks:
        main: 'rga.experiments.sanity_checks.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "rga/*"
            exclude:
                - "**/__pycache__"


- model: recursive_autoencoder
  extends: model-base
  params:
    name: recursive_autoencoder

# - model: recursive_vae
#   extends: model-base
#   params:
#     name: recursive_vae

- model: encoder_num_edges
  extends: model-partial
  params:
    name: encoder_num_edges

- model: recursive_classifier
  extends: model-base
  params:
    name: classifier
