- config: generic-flags
  flags:
    gpus: "1"
    workers: "0"
    checkpoint-monitor: "loss/val"
    lr:
      type: float
    batch_size: 
      type: int
    gradient_clip_val:
      type: float
    seed:
      type: int
    # encoder_hidden_layer_sizes: [512]
    # decoder_hidden_layer_sizes: [512]

- config: model-base
  operations:
    synthetic_grid_small:
        main: 'graph_nn_vae.experiments.synthetic_grid_small.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    synthetic_barabasi_small:
        main: 'graph_nn_vae.experiments.synthetic_barabasi_small.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    synthetic_barabasi_one_100:
        main: 'graph_nn_vae.experiments.synthetic_barabasi_one_100.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    imdb_binary:
        main: 'graph_nn_vae.experiments.imdb_binary.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    imdb_multi:
        main: 'graph_nn_vae.experiments.imdb_multi.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    reddit_binary:
        main: 'graph_nn_vae.experiments.reddit_binary.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
    collab:
        main: 'graph_nn_vae.experiments.collab.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"
                
- config: model-partial
  operations:
    sanity_checks:
        main: 'graph_nn_vae.experiments.sanity_checks.{{ name }}_training'
        flags:
            $include: generic-flags
        output-scalars: off
        sourcecode:
            select:
                - "graph_nn_vae/*"
            exclude:
                - "**/__pycache__"


- model: recurrent_autoencoder
  extends: model-base
  params:
    name: recurrent_autoencoder

- model: recurrent_vae
  extends: model-base
  params:
    name: recurrent_vae

- model: encoder_num_edges
  extends: model-partial
  params:
    name: encoder_num_edges

- model: recurrent_classifier
  extends: model-base
  params:
    name: classifier
